### PR TITLE
use http instead of https for amid

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by fblackburn1** [comment]
!!!!!!!!!!!!!!!! ???????????????? WHY

**Comment by fblackburn1** [comment]
I reverted the merge
We must not validate issue partially

**Comment by bloom1** [comment]
I cannot guess if this is part of a ticket if you don't write it in the PR

**Comment by fblackburn1** [comment]
I can be careful to write it in the title, but the branch name was explicit

**Comment by bloom1** [comment]
Why did you ask me to be the reviewer if the ticket is not ready? I really thought it was done. IMO we should ask for review only when it is ready...

**Comment by fblackburn1** [comment]
> Why did you ask me to be the reviewer if the ticket is not ready

never did that. you should see it in the history

**Comment by bloom1** [comment]
> > Why did you ask me to be the reviewer if the ticket is not ready
> 
> never did that. you should see it in the history if I request someone

DAMN sorry. I saw mergeit and received an email because I am subscribed to this repo :disappointed: that was enough to confuse me.

**Comment by fblackburn1** [comment]
Aah sorry for touching your baby :baby:

**Pull request merged**
