### PR TITLE
tenant helpers: mirror change in lib-python

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/139
Move Tokens into Token classmethod

### CODE REVIEW

**Comment by fblackburn1** [comment]
check experimental

**Comment by fblackburn1** [comment]
recheck
check experimental

**Comment by fblackburn1** [comment]
check experimental

**Comment by fblackburn1** [comment]
> Build failed (experimental pipeline). https://zuul.wazo.community/zuul/t/local/buildset/069967ca18fd40e386f7cbbbb1ba5210
> 
> ❌ [wazo-acceptance-bullseye ](https://zuul.wazo.community/zuul/t/local/build/93120c53229a4c72a1896a740588dd27) **DISK_FULL** in 1h 22m 20s

FYI run went success
```
2024-07-04 15:31:39.458741 | vm-debian-11-m1m | 37 features passed, 0 failed, 0 skipped
2024-07-04 15:31:39.458783 | vm-debian-11-m1m | 151 scenarios passed, 0 failed, 0 skipped
2024-07-04 15:31:39.458787 | vm-debian-11-m1m | 1374 steps passed, 0 failed, 0 skipped, 0 undefined
2024-07-04 15:31:39.458790 | vm-debian-11-m1m | Took 45m38.837s
2024-07-04 15:31:39.523294 | vm-debian-11-m1m |   behave: OK (4151.96=setup[0.95]+cmd[4151.01] seconds)
2024-07-04 15:31:39.523349 | vm-debian-11-m1m |   congratulations :) (4152.09 seconds)
2024-07-04 15:31:47.295632 | vm-debian-11-m1m | ok: Runtime: 1:09:12.261430
```

**Review by sduthil — APPROVED** [review]

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
